services:
  # Backend API
  - type: web
    name: tp-backend
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: tp-postgres-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: tp-postgres-db
    databaseName: mydb
    plan: free
    region: frankfurt
