on:
  push:
    branches: ["main", "develop"]
    paths:
      - "backend/**"
      - "frontend/**"
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * *" # Tous les jours à 2 h du matin
  workflow_dispatch: # Lancement manuel depuis l'interface GitHub
